### ISSUE TITLE
[Toolkit feature]: Flashlight Feature

### ISSUE THREAD

**Issue by skurtyyskirts** [NVIDIAGameWorks/rtx-remix#550] opened 2024-06-27 10:15 UTC
### What is the context of the feature/improvement?

In the RTX-Remix toolkit, while viewing the captures in Asset Replacements, I think it'd be beneficial to add a "flashlight" feature while viewing/moving around the world. As of now, if a scene doesn't have existing lights, I have to manually add a light to a random mesh just to be able to see my scene sometimes. Rather than doing this, I think adding a little flashlight feature while moving around would help while navigating captures.

### Please describe the feature/improvement?

This feature would help assist in scenes that are dim, allowing the modder to see better, without actually adding a light to the scene.  

### What would be your solution? (optional)

...

### Version

2024.3.1

**Comment by sjgillard** [comment] 2024-06-27 17:29
Jira created: REMIX-3218

**Comment by sjgillard** [comment] 2024-06-27 17:57
This is a duplicate of https://github.com/NVIDIAGameWorks/rtx-remix/issues/331 and has been resolved.

**Closed** 2024-06-27 17:58 UTC
Labels: jira, feature, toolkit
