### ISSUE TITLE
Morrowind?

### ISSUE THREAD

**Issue by clumba** [NVIDIAGameWorks/rtx-remix#11] opened 2023-04-12 17:01 UTC
I downloaded the game in steam, copied to the folder remix, but nothing has changed!

What else needs to be done to make the remix work?

**Comment by lunamothxyz** [comment] 2023-04-12 18:05
you need d3d8to9 to translate morrowind's directx 8 calls to 9 : https://github.com/crosire/d3d8to9

**Comment by clumba** [comment] 2023-04-12 19:04
> you need d3d8to9 to translate morrowind's directx 8 calls to 9 : https://github.com/crosire/d3d8to9

It helped, thank you. A remix message appears in the game, but the game hangs after the logo, the main menu does not appear. At the same time alt+x works.

**Comment by lunamothxyz** [comment] 2023-04-12 19:26
The game isn't hanging, it just doesnt render the UI until you tag your UI textures: https://github.com/NVIDIAGameWorks/rtx-remix/wiki/runtime-user-guide#performing-per-game-setup

**Comment by anatolevuc** [comment] 2023-04-12 20:20
Crashes when you get off the ship

**Comment by shad0wshayd3** [comment] 2023-04-12 21:06
Disable Pixel Shaders in the game's launcher to stop it from crashing in exteriors.

**Comment by Splarkszter** [comment] 2023-04-16 04:28
wait wasn't nvidia going to release morrowind on remix?

**Comment by EliteCombineSoldier** [comment] 2023-04-16 08:32
> wait wasn't nvidia going to release morrowind on remix?
> 
> i mean... like the portal RTX thing.

No
It was made clear in the videos
There was a text at the bottom saying it was a technical showcase and would never release

**Comment by OneDeadMachine** [comment] 2023-04-20 15:58
> you need d3d8to9 to translate morrowind's directx 8 calls to 9 : https://github.com/crosire/d3d8to9

Do you have a ready-made config for Morrowind?

**Comment by NV-LL** [comment] 2024-05-06 19:17
Hello! Will you please check on the latest release and let us know if this issue persists? Thank you!

**Comment by nv-ajaus** [comment] 2024-08-27 19:49
Closing as a set up question, not a bug or feature request.

**Closed by nv-ajaus** 2024-08-27 19:49 UTC
Labels: setup-issue
