### ISSUE TITLE
Evil Genius 1 - Cannot load menus for RTX Remix with the game

### ISSUE THREAD

**Issue by Traslogan** [NVIDIAGameWorks/rtx-remix#309] opened 2024-01-22 18:43 UTC
**Describe the bug**
- Evil Genius 1 appears fully incompatible with RTX Remix but it is a DirectX 9.0c game
- Remix Version 0.4
- RTX 4080
- GPU Driver version 546.65
- Latest on Steam

**To Reproduce**
1. Load up the Steam version of Evil Genius 1 via RTX remix
2. Done. Alt-X will not work, the game appears to not be hooked in and there are no RTX Remix menus.

**Expected behavior**
- It is expected that RTX remix would successfully hook into a game that should have a compatible Dx9 version.

**Comment by LoganDark** [comment] 2024-01-23 05:46
You have to manually copy the runtime files into the game directory before it'll load. [see the tutorial video](https://www.youtube.com/watch?v=MQejylcuAeU)

**Comment by LoganDark** [comment] 2024-01-23 17:31
It's not a "fix", that's literally the only way it's intended to be used. With that said, if it doesn't work then that's not supposed to happen, so there may be a bug in RTX Remix after all

**Comment by NV-DM** [comment] 2024-01-24 23:30
REMIX-2673 for tracking.

**Comment by NV-DM** [comment] 2024-01-30 06:08
Not able to reproduce. Closing. For setup help please reach out to the community on Discord.

**Closed by NV-DM** 2024-01-30 06:08 UTC
