### ISSUE TITLE
Portal RTX memory crash on AMD

### ISSUE THREAD

**Issue by KingVulpes** [NVIDIAGameWorks/rtx-remix#582] opened 2024-08-13 19:49 UTC
### Describe the bug

After beating Portal RTX, when the game tries loading the final cutscene, it requests too much memory from the system causing the game to crash. On Steam Deck this not only crashes the game but also the system altogether unless specifying to the game that the Deck only has 16GBs available which then only causes a game crash. This does not happen anywhere else in the game, only on the final cut scene

### How do you reproduce the bug?

Beat the game on AMD hardware and then wait for the final cutscene to try and load

### What is the expected behavior?

It should be loading the final cutscene which would then allow the special cake menu and levels to unlock. Without the final cutscene the game will not recognize it as completed

### Version

0.5.1

**Comment by anon-apple** [comment] 2024-08-14 17:12
What settings are you running on and what GPU?
Portal RTX takes a lot of GPU memory and if you're running it on something like a 8 GB card on say something other than Low graphics it's probably going to attempt to try loading textures that are too high of a quality to fit in VRAM.

**Comment by KingVulpes** [comment] 2024-08-14 21:58
> What settings are you running on and what GPU? Portal RTX takes a lot of GPU memory and if you're running it on something like a 8 GB card on say something other than Low graphics it's probably going to attempt to try loading textures that are too high of a quality to fit in VRAM.
> 
> Of course crashing isn't really ideal so there may be something that can be improved there regardless.

I'm running medium settings with TAA-U set to performance at 1080p on a RX 7600, it is an 8GB card but textures on medium should be set to low if I remember correctly. 
On the Steam Deck, it's the lowest it can go

I should also note that someone on a RX 6700 has reported VRAM ussage up to 18GBs awhile back, this is a card with only 10GBs all on Lower settings

**Comment by NV-LL** [comment] 2024-08-14 22:16
@KingVulpes could you send along any logs from these crashes? We know there was an issue previously with logs not generating on Steam Deck - is that the case here, as well?

**Comment by KingVulpes** [comment] 2024-08-15 01:53
> @KingVulpes could you send along any logs from these crashes? We know there was an issue previously with logs not generating on Steam Deck - is that the case here, as well?

I Won't have my RX 7600 desktop till the 19th, and the only log the Steam Deck isn't generating is the d3d9.exe logs

**Comment by anon-apple** [comment] 2024-08-15 18:32
> I should also note that someone on a RX 6700 has reported VRAM ussage up to 18GBs awhile back, this is a card with only 10GBs all on Lower settings

Yes you can use more VRAM than the dedicated memory available, it just spills into system memory and makes performance terrible. Generally if the texture budgeting logic is configured properly though this shouldn't happen as it'll forcibly reduce texture quality to try and avoid filling up VRAM, so it is odd they'd get it in that state (unless maybe they launched a second application like Omniverse while Remix was running).

**Comment by KingVulpes** [comment] 2024-08-16 00:50
> > I should also note that someone on a RX 6700 has reported VRAM ussage up to 18GBs awhile back, this is a card with only 10GBs all on Lower settings
> 
> Yes you can use more VRAM than the dedicated memory available, it just spills into system memory and makes performance terrible. Generally if the texture budgeting logic is configured properly though this shouldn't happen as it'll forcibly reduce texture quality to try and avoid filling up VRAM, so it is odd they'd get it in that state (unless maybe they launched a second application like Omniverse while Remix was running).

Got my hands on my RX 7600 and things are actually worse, it crashed right after the boss fight, didn't even let me get outside this time.
And can confirm the logs generate on my desktop so i'll provide those
I lowered the graphics even more and added the FSR mod so I can set upscaling even lower

[NvRemixBridge.log](https://github.com/user-attachments/files/16631594/NvRemixBridge.log)
[d3d9.log](https://github.com/user-attachments/files/16631597/d3d9.log)
[hl2_d3d9.log](https://github.com/user-attachments/files/16631598/hl2_d3d9.log)

**Comment by KingVulpes** [comment] 2024-08-16 04:27
> > I should also note that someone on a RX 6700 has reported VRAM ussage up to 18GBs awhile back, this is a card with only 10GBs all on Lower settings
> 
> Yes you can use more VRAM than the dedicated memory available, it just spills into system memory and makes performance terrible. Generally if the texture budgeting logic is configured properly though this shouldn't happen as it'll forcibly reduce texture quality to try and avoid filling up VRAM, so it is odd they'd get it in that state (unless maybe they launched a second application like Omniverse while Remix was running).

Got a new pop up error: Exception on CS thread: DxvkMemoryAllocator: Memory allocation failed. The game will exit now

**Comment by anon-apple** [comment] 2024-08-16 18:57
If you could provide the log files when that exception happens it should give information about which allocation failed. In general though yeah it sounds like there's just not enough memory on those cards. Still odd that it's straight up crashing though as typically the texturing system for instance will try to avoid filling up VRAM in favor of reducing texture quality, so it's still worth looking into I think.

**Comment by NV-LL** [comment] 2024-09-11 16:56
Hi @KingVulpes - checking in again to see if you can provide us with the log files for the exception as per the comment above. We also want to inform you of our stale ticket policy, namely that we will close this ticket as 'went-stale' if it doesn't receive a response within two weeks. Thank you!

**Comment by KingVulpes** [comment] 2024-09-12 23:30
> Hi @KingVulpes - checking in again to see if you can provide us with the log files for the exception as per the comment above. We also want to inform you of our stale ticket policy, namely that we will close this ticket as 'went-stale' if it doesn't receive a response within two weeks. Thank you!

Doesn't seem like I can get the exception to happen again, might have just been because I was streaming at the time it happened and OBS caused it

**Comment by NV-LL** [comment] 2024-10-03 14:18
Hey @KingVulpes, thanks for the update. Could you try to repro again while streaming with OBS? It'd be great to narrow that down if it is the cause.

If you can repro with OBS, would you please update to the latest version of OBS and try again? We know of some bugs on older builds but suspect they should be fixed with current OBS. Thank you!

**Comment by KingVulpes** [comment] 2024-10-03 23:42
> Hey @KingVulpes, thanks for the update. Could you try to repro again while streaming with OBS? It'd be great to narrow that down if it is the cause.
> 
> If you can repro with OBS, would you please update to the latest version of OBS and try again? We know of some bugs on older builds but suspect they should be fixed with current OBS. Thank you!

will do when I have time 👍

**Comment by NV-LL** [comment] 2024-10-24 17:59
Hi @KingVulpes - checking in to see if you've had a chance to re-test this issue and confirm if OBS is in fact the cause. Please let us know what you find. Thanks!

**Closed** 2024-11-20 15:48 UTC
Labels: bug, triage, runtime
