### ISSUE TITLE
Metal Gear Rising Revengeance (DX9 Steam game from 2014) Crashes within 5 seconds Reliably.

### ISSUE THREAD

**Issue by xelectrowolfx** [NVIDIAGameWorks/rtx-remix#201] opened 2023-06-15 03:01 UTC
**Describe the bug**
- A clear and concise description of what the bug is.
- remix-0.2.0
- RTX 4070ti
- Driver 536.23 and 531.41
- Steam game build ID:2987854 App ID: 235460

**To Reproduce**
1. Launch Game
2. Crashes within 5 seconds every-time, while showing title cards.
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11752229/d3d9.log)

**Expected behavior**
MGR:R is a native DX9 game developed in 2014, It should be able to use RTX Remix to its full advantage, however build of remix-0.2.0 crashes MGR:R within seconds of starting the game. 

**Screenshots**
[METAL GEAR RISING REVENGEANCE_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11752226/METAL.GEAR.RISING.REVENGEANCE_d3d9.log)

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/116964236/06c15fc2-28f6-42b9-b5d3-7469347a509e)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11752215/NvRemixBridge.log)

**Comment by xelectrowolfx** [comment] 2023-06-15 03:39
I edited 1 bit in the games exe in HxD to mod out the title cards, without RTX Remix the game loads directely into the main menu, when RTX Remix is enabled and hooked into the game it crashes before you see the main menu.

**Comment by BSoD38** [comment] 2023-06-19 11:00
This game is way too recent for RTX Remix. It only works on DX8-9 games that used a fixed-function pipeline, so pretty much games released before 2006, with a few exceptions.

**Comment by nv-ajaus** [comment] 2023-12-13 00:34
Hi @xelectrowolfx , thank you for bug report! I noticed that the bridge is logging an error in the logs you provided, so we've taken record of this as a bug. To be frank though, as some other commenters have pointed out, even if this crash is fixed, the likelihood of this rtx-remix working well with this application seems low.

**Comment by NV-LL** [comment] 2024-05-07 19:29
Hello @xelectrowolfx! This issue was addressed in a recent release and has been confirmed internally. Will you please test on the latest release and let us know if this persists for you? Thanks!

**Comment by NV-LL** [comment] 2024-05-20 14:21
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.

**Closed by NV-LL** 2024-05-20 14:21 UTC
Labels: bug, triage, runtime
