### ISSUE TITLE
RTS remix launcher doesn't work (black window)

### ISSUE THREAD

**Issue by Shaeiouy** [NVIDIAGameWorks/rtx-remix#412] opened 2024-02-10 01:49 UTC
Hello folks! 
followed the tutorial for launching the application carefully but, just at this step, I already have a problem. Well, on the NVIDIA tutorial "Making Your First Mod with NVIDIA RTX Remix" the launcher with the RTX mod crashes my PC... At least, I have a black window which makes my PC crash and nothing else. ..while in principle, I should have (as this tutorial shows me) a rendering of the sample with the rays. I don't understand why I don't have all of this. And there is also nothing that happens when I launch a game with the application (for example Tomb Raider 3), I press ALT and X but... nothing happens. Does anyone have any idea how to solve my problem? 
- Which Remix version (the last one: 2024 1.1)
- Which GPU : 3090
- Which GPU driver version : 551.23
- Which game build : first of all, I tried the NVIDIA tutorial with their remix sample.exe, but it doesn't work. Then I tested it with Tomb raider 3, from Steam. Don't work either.
![Capture d'écran 2024-02-10 023811](https://github.com/NVIDIAGameWorks/rtx-remix/assets/159596884/974a63d2-a798-4547-a6c1-545c3bfc320c)
![Capture d'écran 2024-02-10 023956](https://github.com/NVIDIAGameWorks/rtx-remix/assets/159596884/6034bb5f-0472-4745-a0c4-aaa4f60f085f)
![Capture d'écran 2024-02-10 024013](https://github.com/NVIDIAGameWorks/rtx-remix/assets/159596884/5ddb87a2-64dc-4453-a40f-5f8173e68bff)

**Comment by nvdamien** [comment] 2024-02-14 23:40
Assigned to @nv-ajaus  . It looks like a runtime problem (the sample that has a black screen).

**Comment by NV-DM** [comment] 2024-02-21 23:22
Closing as duplicate of https://github.com/NVIDIAGameWorks/rtx-remix/issues/415

**Closed by NV-DM** 2024-02-21 23:22 UTC

**Comment by Shaeiouy** [comment] 2024-02-22 16:32
"#415" was closed without providing me with an answer to my problem. I still don't have a solution to this problem. I also posted on discord and no one responded...

> Closing as duplicate of #415

"#415" was closed without providing me with an answer to my problem. I still don't have a solution to this problem. I also posted on discord and no one responded...

**Comment by nvdamien** [comment] 2024-02-22 17:28
#415 is not closed

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/128181406/a8d94c83-6494-4b19-9643-01a832258c10)
