### ISSUE TITLE
I am trying to launch Remix but it does not let me.

### ISSUE THREAD

**Issue by bg-peole** [NVIDIAGameWorks/rtx-remix#387] opened 2024-01-30 11:14 UTC
**Describe the bug**
- So I am trying to open Remix through Omniverse and the app launches but it crashes right on the point of where I showed on the screenshot below. I also tried to launch it from install.bat and also got an error that I have also attached bellow. I tried re-installing it but it still did not work. How do I fix it?
- Which Remix version (include branch and commit info for dxvk and bridge if not a stable build)
- 4060 mobile
- 551.23
- N/A

**Attach files!**
- NvRemixBridge.log - https://github.com/NVIDIAGameWorks/rtx-remix/files/14096792/NvRemixBridge.log
- d3d9.log - https://github.com/NVIDIAGameWorks/rtx-remix/files/14096803/kit_d3d9.log
- The game specific log will be named gamename_d3d9.log - N/A
- Used rtx.conf - N/A
- For crashes also attach dump files: {.dmp} for CPU side crashes and {.nv-gpudmp and shaderDebugInfo folder} for GPU side crashes. Automatic GPU dumps can be enabled by setting "dxvk.enableAftermath = True" in dxvk.conf. Zip these files before uploading them.
  Note, the dumps may contain personally identifiable information.

**To Reproduce**

**Expected behavior**
- A clear and concise description of what you expected to happen.

**Screenshots**
https://rb.gy/3e6t9c
https://rb.gy/8ofdix

**Comment by XanaXCODE** [comment] 2024-01-30 16:47
same

**Comment by po-trottier** [comment] 2024-01-30 21:46
Hi! We'd need your app logs to be able to find the crash dumps!
They should be here: `C:\Users\YOUR_USERNAME\.nvidia-omniverse\logs\Kit\RTX Remix\2024.1`

**Comment by po-trottier** [comment] 2024-01-30 23:14
This is a duplicate of: https://github.com/NVIDIAGameWorks/rtx-remix/issues/382 
Will track there

**Closed by po-trottier** 2024-01-30 23:14 UTC
Labels: bug, toolkit, triage

**Comment by bg-peole** [comment] 2024-01-31 09:14
> Hi! We'd need your app logs to be able to find the crash dumps! They should be here: `C:\Users\YOUR_USERNAME\.nvidia-omniverse\logs\Kit\RTX Remix\2024.1`

https://github.com/NVIDIAGameWorks/rtx-remix/files/14109543/kit_20240130_102343.log

**Comment by bg-peole** [comment] 2024-02-02 09:36
> Hi! We'd need your app logs to be able to find the crash dumps! They should be here: `C:\Users\YOUR_USERNAME\.nvidia-omniverse\logs\Kit\RTX Remix\2024.1`

Here is the new log without the cache issue. https://github.com/NVIDIAGameWorks/rtx-remix/files/14138170/kit_20240202_090701.log
