### ISSUE TITLE
Command & Conquer: Renegade

### ISSUE THREAD

**Issue by sibercat** [NVIDIAGameWorks/rtx-remix#106] opened 2023-04-18 22:11 UTC
Remix version - 0.1.1
GPU - 3070 Ti
GPU driver version - 531.68
Game build - EA App d3d8to9

Command & Conquer: Renegade - Direct3D	8.1
Using just d3d9 will start the game but will not launch Remix, using d3d8to9 will try to start the game but will be stuck on start up loading, _windows spinning icon_ then just crash, and will stop loading.

Attached logs

[_except.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/11266739/_except.txt)
[_logfile.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/11266740/_logfile.txt)
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11266742/d3d9.log)
[Game_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11266743/Game_d3d9.log)
[metrics.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/11266744/metrics.txt)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11266745/NvRemixBridge.log)
[sysinfo.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/11266746/sysinfo.txt)
[WWConfig_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11266747/WWConfig_d3d9.log)

**Comment by mralexs5** [comment] 2023-04-19 14:40
#28 
We have discovered you need at least a CD copy to run it with remix, not tested with TFD copies. TUC version at the moment is not compatible

**Comment by Aokromes** [comment] 2023-05-13 00:09
imho this ticket must be closed since it's duplicate of #28

**Closed** 2023-05-24 00:52 UTC
Labels: bridge-server-init
