### ISSUE TITLE
nullptr Crash During Startup - Driver: Parallel Lines

### ISSUE THREAD

**Issue by anchorlightforge** [NVIDIAGameWorks/rtx-remix#272] opened 2023-10-25 00:40 UTC
**Describe the bug**
- When attempting to start up Driver: Parallel Lines, deferring surface creation will result in Remix silently crashing.  This is also the default setting when including dxvk.conf.
- Version: Remix 0.3.0 + DXVK Remix 8a18639-290-debugoptimized
- GPU: Nvidia Geforce RTX 3080
- Driver: Nvidia Studio 536.67
- Driver: Parallel Lines (GOG)

**Attach files!**
The following file includes all relevant logs as well as a dump file for the build of Remix listed above.
[DriverPLCrashRepro-8a18639.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/13146743/DriverPLCrashRepro-8a18639.zip)

**To Reproduce**
1. Set up Driver: Parallel Lines using the rtx.conf and dxvk.conf files included (dxvk.conf's config will directly result in a crash)
2. OPTIONAL: Rename or delete the "FMV" folder in the game installation for better performance and stability
3. Open DriverParallelLines.exe
4. The game will open and silently exit with a nullptr exception.

**Expected behavior**
- Game should initialize and enter fullscreen mode without crashing.

**Comment by NV-DM** [comment] 2023-10-25 21:47
REMIX-2284 for tracking.

**Comment by anchorlightforge** [comment] 2023-10-27 07:07
Today I reproduced this exact issue using Slave Zero (GOG).  This was done using RTX Remix 0.3.0 Debug-Optimized + DXVK Remix 88ed51a Debug-Optimized.  

I will not change the ticket above as Driver is much easier to set up.  However, just in case the extra case is useful I'll be including instructions for how to set up Slave Zero for testing:

1. Download and install the GOG release of Slave Zero
2. Download the Direct3D Patch from PCGW that restores D3D support present in the original game releases but absent from GOG: https://community.pcgamingwiki.com/files/file/546-slave-zero-direct3d-patch/
3. After extracting the contents to Slave Zero, follow the patch's readme instructions to enable 32-bit D3D
4. Set up RTX Remix inside the game installation folder and use ElishaCloud's DxWrapper with the included 
[dxwrapper.ini file](https://github.com/NVIDIAGameWorks/rtx-remix/files/13185900/dxwrapper.zip) (zipped to include in issue)
5. Similar to Driver: Parallel Lines, set d3d9.deferSurfaceCreation to true in dxvk.conf
6. Game will crash on startup when attempting to open in fullscreen and create a dump file

Dump file and logs included below.

[d3dSlaveZeroCrashLogs.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/13185935/d3dSlaveZeroCrashLogs.zip)

**Comment by anon-apple** [comment] 2024-04-08 22:47
I tested Driver: Parallel Lines with the steps you provided using a more recent version of Remix and the bridge and cannot seem to reproduce this crash. The game is still fairly unstable and usually deadlocks trying to launch for some reason (something to do with how it tries to go fullscreen I am guessing), but it does actually launch successfully sometimes.

I do know why the nullptr crash as reported happened though so I might be able to add some safety checks to ensure it doesn't happen in other cases. Can you confirm though that using a more recent build of Remix that this crash at least doesn't happen anymore? (I still don't expect the game to work perfectly, but if this nullptr issue was fixed by recent changes to how fullscreen stuff is handled we can probably close this issue)

**Comment by NV-LL** [comment] 2024-05-17 14:55
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.

**Comment by NV-LL** [comment] 2024-05-17 14:55
Closing

**Comment by NV-LL** [comment] 2024-05-17 14:56
Thank you for reaching out. We're going to close this ticket due to an extended period with no response. If the issue persists for you on the latest build, please open a new ticket.

**Closed by NV-LL** 2024-05-17 14:56 UTC
Labels: jira
