### ISSUE TITLE
Windows Defender detects nvremixlauncher as trojan

### ISSUE THREAD

**Issue by Swpn0neel** [NVIDIAGameWorks/rtx-remix#141] opened 2023-05-08 14:53 UTC
Windows Defender is detecting nvremixlauncher as trojan when I'm trying to launch it.
![image](https://user-images.githubusercontent.com/121167506/236857076-68cd8420-8f4b-4e45-9b92-0848493a911c.png)

**Comment by AlexDunn** [comment] 2023-05-08 19:21
This is a false detection, and I believe this was fixed with remix-0.1.1, can you confirm?

**Comment by Aokromes** [comment] 2023-05-13 00:02
duplicate of #5

**Comment by AlexDunn** [comment] 2023-05-24 01:07
Closing as dupe.

**Closed by AlexDunn** 2023-05-24 01:07 UTC
