### ISSUE TITLE
[Toolkit bug]: Left Handed Z-Up game is upsidedown in toolkit

### ISSUE THREAD

**Issue by mmdanggg2** [NVIDIAGameWorks/rtx-remix#312] opened 2024-01-22 21:42 UTC
### Describe the bug

I have a game (Unreal) that uses a Left handed Z-Up coordinate system and I have marked it as such in the remix menu. The captures and cameras load in fine but everything is upsideown, up is towards -Z which makes navigating quite difficult!

### How do you reproduce the bug?

1. Find a game that uses a left handed Z up coordinate system and capture a scene
2. Load that scene in remix toolkit
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/3161587/d3dc2c31-2a03-42e2-aa90-0f226f847e95)
Attached capture:
[2024-01-22_21-28-35.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14015693/2024-01-22_21-28-35.zip)

### What is the expected behavior?

The toolkit should load the scene the correct way around!

### Version

2024.1.1

**Comment by xbei-nv** [comment] 2024-01-22 21:53
Have you sync to the latest dxvk-remix code? We have merged lots of fixes and asaik this issue has been solved.

**Comment by mmdanggg2** [comment] 2024-01-22 22:01
Grabbed the latest from main as of 2hrs ago (https://github.com/NVIDIAGameWorks/dxvk-remix/commit/d1ba9c9f2f08652bd2a4d05adedf34d2fc63d975) and it is the right way up now but everything is mirrored now:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/3161587/6fecdba4-8a17-4df5-9934-e5d55d41421a)

**Comment by xbei-nv** [comment] 2024-01-22 22:06
How does it looks like in the real game?

**Comment by xbei-nv** [comment] 2024-01-22 22:07
I have tested multiple games with exactly same setups (zUP + LHS), haven't seen any mirror issues

**Comment by mmdanggg2** [comment] 2024-01-22 22:09
As the first capture:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/3161587/8570b5ba-a53e-49ed-9c1d-3096f3f643e7)

**Comment by mmdanggg2** [comment] 2024-01-22 22:21
If I disable both Zup and LH then it will come in correctly but in the wrong orientation:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/3161587/bfd4176e-8901-405f-b8b3-2a053c90bad4)
And then only enabling Z up it is correctly oriented but mirrored. Setting LH from that seems to do nothing different.

**Comment by xbei-nv** [comment] 2024-01-22 22:23
That's very interesting, I tried many more tests with left handed Z up coordinate system but still can't reproduce this

**Comment by xbei-nv** [comment] 2024-01-22 22:41
Which game are you testing? Also, could you create a new issue ticket to report bug for this specific game? We need to close this one b/c it's not upside down issue anymore and not generic to all games.

**Comment by mmdanggg2** [comment] 2024-01-22 22:44
Ok, sure. It's Unreal Tournament but I've written a new render plugin for it.

**Comment by xbei-nv** [comment] 2024-01-22 22:45
Did you change any transformation matrix? Especially the projection matrix

**Comment by KCDQYaniss** [comment] 2024-01-22 22:50
Same problem here with GTA San Andreas, Z-Up + left-handed it ends up upside down, I updated everything of course

**Comment by mmdanggg2** [comment] 2024-01-22 22:52
> Did you change any transformation matrix? Especially the projection matrix

I'm using the DirectX
XMMatrixPerspectiveFovLH for projection
XMMatrixLookToLH for view

**Comment by xbei-nv** [comment] 2024-01-22 22:56
> Same problem here with GTA San Andreas, Z-Up + left-handed it ends up upside down, I updated everything of course

You need to update to https://github.com/NVIDIAGameWorks/dxvk-remix/commit/d1ba9c9f2f08652bd2a4d05adedf34d2fc63d975 . I tested exactly same thing 1 minute ago and no upside-down issue.

**Comment by xbei-nv** [comment] 2024-01-22 22:58
> > Did you change any transformation matrix? Especially the projection matrix
> 
> I'm using the DirectX XMMatrixPerspectiveFovLH for projection XMMatrixLookToLH for view

That could be issue if it's dx matrix. How does it looks like without your plugin

**Comment by mmdanggg2** [comment] 2024-01-22 23:11
Well, it's a total mess since the game transforms the world on the cpu around an identity matrix view normally.
Z up and LH seem to do nothing here:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/3161587/9e31eecb-f6f9-4c46-9d2f-b5a2fb7c9556)
Here's an apitrace from my plugin version if that helps: 
[UnrealTournament_apitrace.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/14016364/UnrealTournament_apitrace.zip)

**Comment by xbei-nv** [comment] 2024-01-22 23:44
Is this screenshot from your plugin version or it's original game?

**Comment by mmdanggg2** [comment] 2024-01-22 23:45
> Is this screenshot from your plugin version or it's original game?

That's from the game, unmodified, basically unusable.

**Comment by KCDQYaniss** [comment] 2024-01-22 23:51
> > Same problem here with GTA San Andreas, Z-Up + left-handed it ends up upside down, I updated everything of course
> 
> You need to update to [NVIDIAGameWorks/dxvk-remix@d1ba9c9](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/d1ba9c9f2f08652bd2a4d05adedf34d2fc63d975) . I tested exactly same thing 1 minute ago and no upside-down issue.

Nope, issue still there :/

**Comment by xbei-nv** [comment] 2024-01-23 00:04
> > > Same problem here with GTA San Andreas, Z-Up + left-handed it ends up upside down, I updated everything of course
> > 
> > 
> > You need to update to [NVIDIAGameWorks/dxvk-remix@d1ba9c9](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/d1ba9c9f2f08652bd2a4d05adedf34d2fc63d975) . I tested exactly same thing 1 minute ago and no upside-down issue.
> 
> Nope, issue still there :/

Are you sure you have updated all binaries and run game/capture again? You need to compile the latest code and update DLLs. This is one of the first games on my test list when solve this issue, so I think it should work well.

**Comment by KCDQYaniss** [comment] 2024-01-23 00:07
> > > > Same problem here with GTA San Andreas, Z-Up + left-handed it ends up upside down, I updated everything of course
> > > 
> > > 
> > > You need to update to [NVIDIAGameWorks/dxvk-remix@d1ba9c9](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/d1ba9c9f2f08652bd2a4d05adedf34d2fc63d975) . I tested exactly same thing 1 minute ago and no upside-down issue.
> > 
> > 
> > Nope, issue still there :/
> 
> Are you sure you have updated all binaries and run game/capture again? You need to compile the latest code and update DLLs. This is one of the first games on my test list when solve this issue, so I think it should work well.

Yep, updated everything,
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/100313819/158d456a-9621-41d9-9cc5-1c92073c769d)

**Comment by RuneStorm** [comment] 2024-01-23 09:16
I am running into a similar issue with Unreal Tournament 2004. 
Capturing without any changes gives me a 90° rotated and flipped capture because in UE Z is up, so changing it gives me the correct orientation, but flipped along the X. When I toggle Left handed however, the entire scene breaks.
Left Handed seems to breaks a lot of things. By the looks of it, the front faces get inverted too which is unexpected behavior.
![Ingame-Screenshot](https://github.com/NVIDIAGameWorks/rtx-remix/assets/5238589/b0835594-9fcf-4fd1-9fa8-08d3ec26ed54)
![capture_orientation](https://github.com/NVIDIAGameWorks/rtx-remix/assets/5238589/583c2772-f1f6-462d-811c-5cf049542ba7)

**Comment by xbei-nv** [comment] 2024-01-23 18:42
@RuneStorm @mmdanggg2 OK I guess there're something not works well on UE based games, we will investigate it.

**Comment by xbei-nv** [comment] 2024-01-23 18:43
> > > > > Same problem here with GTA San Andreas, Z-Up + left-handed it ends up upside down, I updated everything of course
> > > > 
> > > > 
> > > > You need to update to [NVIDIAGameWorks/dxvk-remix@d1ba9c9](https://github.com/NVIDIAGameWorks/dxvk-remix/commit/d1ba9c9f2f08652bd2a4d05adedf34d2fc63d975) . I tested exactly same thing 1 minute ago and no upside-down issue.
> > > 
> > > 
> > > Nope, issue still there :/
> > 
> > 
> > Are you sure you have updated all binaries and run game/capture again? You need to compile the latest code and update DLLs. This is one of the first games on my test list when solve this issue, so I think it should work well.
> 
> Yep, updated everything, ![image](https://private-user-images.githubusercontent.com/100313819/298763138-158d456a-9621-41d9-9cc5-1c92073c769d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzUzMDAsIm5iZiI6MTcwNjAzNTAwMCwicGF0aCI6Ii8xMDAzMTM4MTkvMjk4NzYzMTM4LTE1OGQ0NTZhLTk2MjEtNDFkOS05Y2M1LTFjOTIwNzNjNzY5ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxODM2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NWM3MGFhNTk0MGJjNDVhZTgzYjk2MjIyZTAxZWRlNTliNDJjNGQ1Y2VlNTExMDEzMWYzZDFkYzkwYTBmMzY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.s5lCFU9TqWBWlj1QYIalaS8YhaQhnsrTq1yPAdUQKn8)

OK I think it's not related to runtime capture, something goes wrong with the remix editor. We got different results b/c we were opening captures on different apps.

**Comment by Kiro32** [comment] 2024-01-24 23:04
Yeah it might be a UE issue. I'm trying it on  Star Wars Republic Commando (UE2) and the capture is also on the wrong axis. Makes the toolkit editor super disorienting to use

**Comment by z1chsr** [comment] 2024-01-27 00:11
having the same problem, this game is NOT an UE based game.
![flippedfaces](https://github.com/NVIDIAGameWorks/rtx-remix/assets/46182046/07ec56c5-7a2d-487f-95c2-7c323883d61e)

**Comment by xbei-nv** [comment] 2024-01-30 19:33
Hi we have got a fix for this one, you can quickly check the fix on main branch (release version will be updated soon)

**Comment by z1chsr** [comment] 2024-01-30 19:36
wooo, thx for the update!

**Comment by xbei-nv** [comment] 2024-01-30 22:36
Confirmed this upside-down issue in toolkit is solved.

**Closed by xbei-nv** 2024-01-30 22:36 UTC
Labels: bug, toolkit, triage
