### ISSUE TITLE
'[Toolkit bug]: remix::dxvk_D3D9'has failed. error code1

### ISSUE THREAD

**Issue by TheHuntsmanbuh** [NVIDIAGameWorks/rtx-remix#430] opened 2024-02-27 09:01 UTC
### Contact Details (Optional)

popopepes406@gmail.com

### Describe the bug

after the newest release of nvidia remix toolkit (2024.2.1) remix does this on startup:
![Screenshot 2024-02-27 195247](https://github.com/NVIDIAGameWorks/rtx-remix/assets/158553946/02cea0a5-4cc6-43c8-aa86-3bb3854f72aa)

im not sure why but i have updated drivers and checked on github and on the discord and i haven't found anyone with a similar issue. 
here's my crash log for anyone that knows anything about this: [kit_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14416911/kit_d3d9.log)
(i hope this isn't something obvious)

### How do you reproduce the bug?

1. launch NVidia rtx toolkit
2. get this error

### What is the expected behavior?

the toolkit should start-up without the error message

### Version

2024.2.1

**Comment by TheHuntsmanbuh** [comment] 2024-02-27 09:06
might have uploaded the wrong log so here's the most recent one's:  
[kit_20240105_110434.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14416963/kit_20240105_110434.log)
[kit_20240105_124107.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14416972/kit_20240105_124107.log)
[kit_20240112_113512.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14416977/kit_20240112_113512.log)
[kit_20240117_070031.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14416985/kit_20240117_070031.log)

**Comment by nvdamien** [comment] 2024-02-27 18:03
@sultim-t-nv

**Comment by pandorazero** [comment] 2024-02-27 19:25
I have the same problem, I hope there will be a solution :)
![32423rfdffd](https://github.com/NVIDIAGameWorks/rtx-remix/assets/16753898/53ba1d8e-64f1-434b-9280-c31001178192)

**Comment by nvdamien** [comment] 2024-02-27 22:23
Should we centralize this bug in https://github.com/NVIDIAGameWorks/rtx-remix/issues/382 ?

**Comment by pandorazero** [comment] 2024-02-27 22:43
> May you also provide `kit_d3d9.log`? Usually it's at
> `C:\Users\<YOUR_USER_NAME>\AppData\Local\ov\pkg\rtx-remix-2024.2.1`
Here you go, look what the problem is
[kit_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/14426433/kit_d3d9.log)

**Comment by NV-DM** [comment] 2024-02-28 23:16
Closing as duplicate of https://github.com/NVIDIAGameWorks/rtx-remix/issues/382. REMIX-2719

**Closed by NV-DM** 2024-02-28 23:16 UTC
Labels: bug, toolkit
