### ISSUE TITLE
[Toolkit bug]: AI Tools fail when output drive is different than the input one

### ISSUE THREAD

**Issue by xKrasheR** [NVIDIAGameWorks/rtx-remix#386] opened 2024-01-30 04:02 UTC
### Describe the bug

The GeneratePBRMaterial will fail if the input folder (e.g. D:\Game\rtx-remix\captures\textures) is on a different drive than the output folder (e.g. G:\AI_Output)

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/27704558/06a83650-4dd2-41a4-8f16-0368ec67e3db)

### How do you reproduce the bug?

The information is written above.

### Version

2024.1.1

**Comment by po-trottier** [comment] 2024-01-30 04:23
I'm able to run an inference using an input on `C:/` and output on `S:/`, vice-versa. I will need a clearer repro to know what the issue is here.

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/41876093/a4af1a0b-81dc-4f60-9959-7dfc5dade6db)
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/41876093/04ddcd7d-55a3-4adc-9dc5-2ba86b1c82c7)

Could you try:
- Copy the input on the same drive and the output 
- Output to any other drives you have on your PC (C:/ ?)
- Any other steps that could help us isolate the exact cause of this issue

**Comment by Kiro32** [comment] 2024-01-30 18:33
I would second trying it on your C:/ drive. Recently I moved my project files to my C:/ drive while my game is on F:/. So far I've had no issues with it, but I do recall getting an error with that _exact_ phrasing. The issue was either related to spaces in folder names or the output being in the rtx-remix folder. I forget which unfortunately, but it might help you nail down reproduction of the issue.

So I'd try moving your output to C:/ first. If nothing changes, keep an eye on spaces in folder names leading to your output directory. If that doesn't work, there's likely something else going on.

**Comment by po-trottier** [comment] 2024-02-01 00:38
If a space is in the input or output and the input texture is a DDS I can reproduce a different crash but a crash nonetheless. 

For me the progress stays stuck at 50% and I get a crash in the logs:
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/41876093/5e3a4f03-f749-4a9b-ad92-31a4e8ccfd6a)

**Comment by po-trottier** [comment] 2024-02-01 00:42
Tracked under REMIX-2731

**Comment by NV-LL** [comment] 2024-05-02 22:37
Closing since fix was confirmed internally with 2024.3.0. Please let us know if you encounter this again.

**Closed by NV-LL** 2024-05-02 22:37 UTC
Labels: bug, jira, toolkit
