### ISSUE TITLE
This Game requires at least Shader Model 3.0

### ISSUE THREAD

**Issue by HexPa5** [NVIDIAGameWorks/rtx-remix#101] opened 2023-04-18 08:26 UTC
Batman Arkham Asylum and Batman Arkham City (with disabled DX11 features) use Shader model 3.0 It looks like these games engines based on Unreal Engine 3 use never or older version of graphic shaders that are not compatible with RTX Remix software. Can you add support for these games? Thank you

**Comment by Aokromes** [comment] 2023-04-18 08:39
duplicate of https://github.com/NVIDIAGameWorks/rtx-remix/issues/98

**Comment by NV-DM** [comment] 2023-10-04 22:22
Closing as duplicate of https://github.com/NVIDIAGameWorks/rtx-remix/issues/98 

Shader-based games are not in scope for Remix, as it's a difficult technical problem to solve. We therefore have no plans to support them for now. (There is extremely limited support for vertex shaders in some games, but it's focused on specific use cases that we can currently support.)

**Closed** 2023-10-04 22:23 UTC
