### ISSUE TITLE
[Runtime bug]: Transparency Issue in Half-life 2

### ISSUE THREAD

**Issue by RyzenDew** [NVIDIAGameWorks/rtx-remix#407] opened 2024-02-06 06:42 UTC
### Describe the bug

So Windows and Eyes and many other things are broken in Half-life 2 and not sure how the team remastering it is working around it but here is the issue 

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/84041391/7dfdfa04-f574-4c73-ad40-3181f6196cc2)
This is a windows and it's transparent but in the RTX remix toolkit it's solid 
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/84041391/3380661b-d7e7-43ba-a708-686a6c1adf12)
and because of this the light does not get into the building properly.

now we got 2 types of eye bugs : 
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/84041391/c77a3715-054f-40f6-9bb6-8ba7eb2380dc)
and 
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/84041391/0d020389-7d75-49ac-8578-aa77b68ed933)

pupil is rendering but the whites of the eyes are not .. 

### How do you reproduce the bug?

capture any NPC or near any window

### What is the expected behavior?

The toolkit should... handle transparency better

### Version

2024.1.1

**Comment by nvdamien** [comment] 2024-02-06 21:02
Hi,

Thanks for the report. It looks like a rendering bug. The rendering team will take care of it.

**Comment by nvdamien** [comment] 2024-02-07 23:17
So it looks like this is a setup problem. We have 2 types on materials in RTX Remix:
- opaque
- transparency

For transparent material, you need to click here to create a transparency material:

![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/128181406/79a0d1a2-ea1b-4dc5-ab08-a8580a1e2a14)

From here, you will have a transparency material that you can use for this setup.

Please tell me if this is fixing your issue.

We need to update the documentation.

**Comment by RyzenDew** [comment] 2024-02-12 17:35
> So it looks like this is a setup problem. We have 2 types on materials in RTX Remix:
> 
>     * opaque
> 
>     * transparency
> 
> 
> For transparent material, you need to click here to create a transparency material:
> 
> ![image](https://private-user-images.githubusercontent.com/128181406/303164998-79a0d1a2-ea1b-4dc5-ab08-a8580a1e2a14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NTk1MTcsIm5iZiI6MTcwNzc1OTIxNywicGF0aCI6Ii8xMjgxODE0MDYvMzAzMTY0OTk4LTc5YTBkMWEyLWVhMWItNGRjNS1hYjA4LWE4NTgwYTFlMmExNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxNzMzMzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGFiNDM4MzMyYmJjMmVjZDU5MjFlY2ZiZGJhNmVmOGQxMTEwNjg2ZmViODU0NzA0NmQyYTNhZGRlYWRmZTE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JrFP9gk6m-HD7cbskUFYLuNRHGrTMrsh69gAdyiW5rk)
> 
> From here, you will have a transparency material that you can use for this setup.
> 
> Please tell me if this is fixing your issue.
> 
> We need to update the documentation.

it was not a setup issue but just missing stuff in RTX remix to fix the issue you need portal prelude files which is just silly see the eyes are an offset decal which the current RTX remix has no support for

**Comment by nvdamien** [comment] 2024-02-12 19:29
> you need portal prelude files 

Do you mean the .conf file?

**Comment by NV-WendyGram** [comment] 2024-02-22 23:37
@nvdamien Could you provide me information on what I need to update in the documentation?

**Comment by nvdamien** [comment] 2024-02-22 23:42
@NV-WendyGram  It looks like it was not a Toolkit setup problem, but the .conf file that was missing.
Closing. Please re-open if the problem is not fixed.

**Closed by nvdamien** 2024-02-22 23:42 UTC
Labels: documentation
