### ISSUE TITLE
Scrapland Remastered - Crash on Level Load (Longer Sessions)

### ISSUE THREAD

**Issue by anchorlightforge** [NVIDIAGameWorks/rtx-remix#262] opened 2023-10-13 22:23 UTC
**Describe the bug**
- Description: After about ten minutes of gameplay, Scrapland Remastered will infinitely load on next death, quit, or area change and become unresponsive.
- Remix ver.: DXVK 65dab8b Debug-Optimized, Bridge 5aa73bc Debug-Optimized
- GPU: Nvidia Geforce RTX 3080
- Driver: Nvidia Studio 536.67
- Version: GOG

**Attach files!**
- [ScraplandRTXSaves.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/12899628/ScraplandRTXSaves.zip)
  - Extract the contents to User\<user>\Documents\MercurySteam\Scrapland\
- [gamelogs.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/12899635/gamelogs.zip)
  - D3D9 logs + old DxWrapper log + in-game logs (in-game logs are plain HTML format, and are cluttered due to letting the game run idle for extended time)
- [gameconf.zip](https://github.com/NVIDIAGameWorks/rtx-remix/files/12899818/gameconf.zip)
  - Includes conf files to place inside the Scrapland Remastered folder.
- A DMP file is not created on crash.

Installation instructions (to be replaced with link to repo):
- Install game from GOG
  - Steam will work as well but that version has anti-debug protection in place.
- Place the contents of gameconf.zip inside Scrapland Remastered
- Place the contents of ScraplandRTXSaves.zip inside Documents/MercurySteam/Scrapland (Create if it doesn't exist)
  - If using the Steam version, run the game at least once then replace the contents of the subfolder with an ID string for a name
  - Verify that Scrap.cfg is read-only
- Rename the "Video" folder
- Install DXVK and Bridge Remix to Scrapland Remastered/bin
- Open game (Bin/Scrap.exe) using a new shortcut with the launch arguments ` -console -debug:10 -enginedebuglevel:10`
  - When using the debug console shortcut all game info will be dumped to log.html and logAI.html.

**To Reproduce**
1. Open Scrap.exe
2. Click on "Single Player," then "Load Game" and select a map (e.g. Press Building)
3. Play the game with the window in focus for about ten minutes
4. Change stages by taking the Tubular Transport or an Elevator (Teleporters usually don't trigger this), or by dying without extra lives (only works if not on Jail stage).
5. When the player changes levels, the game will freeze forever before the loading screen displays.

**Expected behavior**
- The player should be able to load between areas freely by using the Tubular Transport areas.
- Other unrelated crashes:
  - On changing game settings, the game will crash with a message saying Vp8.Width was invalid.
  - On selecting "New Game" the game will crash pointing to a code error.

**Screenshots**
- If applicable, add screenshots to help explain your problem.
- If it is a visual issue where the raytraced version is wrong/different in comparison to the rasterized version, attach a screenshot of the rasterized version for reference. You can view the rasterized version by disabling raytracing (available in debug and debugOptimized builds).

**Comment by anchorlightforge** [comment] 2023-10-14 05:29
After further testing this appears to be related to content loading in general, as I was able to reproduce this crash by entering the GDB terminal and selecting a character that was not present in the scene already.

**Comment by Kamilkampfwagen-II** [comment] 2023-10-14 08:34
This might be related to the issue Chess Titans has? Similar scenario but with replacement assets. If you try to load a scene with lots of assets currently unpresent in the scene, it'll become unresponsive.
Chess Titans is already problematic (driver crashes) so my assumption is not reliable.

**Comment by nv-ajaus** [comment] 2023-10-18 23:08
Hi @anchorlightforge , can you please try reproducing this issue again with a release build of rtx-remix? Also, are the game options `-console -debug:10 -enginedebuglevel:10` necessary for launching the game with remix? If not, could you please attempt the repro without them?

**Comment by anchorlightforge** [comment] 2023-10-20 17:23
Thanks for your patience.  I printed the debug info because I figured it couldn't hurt but I can confirm that Remix works fine without the extra debug info.  I have a busy day ahead but some time in the next 24 hrs I'll try to update the logs for this, #263 and #264.

**Comment by anchorlightforge** [comment] 2023-10-23 06:25
I can confirm that this was occurring with the debug commands disabled and I _believe_ I tested this on Release before moving to Debug-Optimized.  However, I've been unable to reproduce this bug again as of late.  In the past, the loading triggers that seemed to cause this to occur were either while accessing the GDB and switching characters to ones that did not appear in the stage (e.g. Chief of Bankers or Police in the Gambler's Den) or while switching areas entirely.

I've been testing this all week and I simply can't get this to occur again, even on the same Remix version and in debug-optimized.  I'll continue to investigate.

**Comment by nv-ajaus** [comment] 2023-10-26 03:52
Thank you for trying to reproduce this issue again, anchorlightforge. Since this doesn't seem to be reproducible at the moment, I'm going to go ahead and close it for now. If it starts happening again please let us know! And thank you for filing these issues separately, it really helps us when trying to understand and manage issues.

**Closed by nv-ajaus** 2023-10-26 03:52 UTC
