### ISSUE TITLE
[Toolkit feature]: Use Symbolic links instead of Junctions when creating projects.

### ISSUE THREAD

**Issue by Steven-OConnell** [NVIDIAGameWorks/rtx-remix#403] opened 2024-02-04 19:23 UTC
### Contact Details (Optional)

I'm in the Remix Discord, Username: steven_oconnell

### What is the context of the feature/improvement?

The current project linking system only works with local directories, using a NAS or Server is not possible with Junctions as they only work with local storage devices.

### Please describe the feature/improvement?

The Creator Toolkit currently uses Junctions to achieve the necessary file linking used in projects, however this method comes with the restriction of only working with local storage devices. Symbolic links will achieve the same results with the additional benefit of working with remote storage devices that support SMB.
This is a huge thing for anyone who works off a NAS or Server.

If Junctions continue to be used users will be FORCED to create project directories on their local storage device, it’s a very unusual behaviour for a modern application to not support the use of network locations.

The main difference between Junctions and Symbolic links that are the following;
![Symlink](https://github.com/NVIDIAGameWorks/rtx-remix/assets/54165616/766f8c05-cfcd-4ea9-a10c-4edf9d414e99)

### What would be your solution? (optional)

In order to change this all that would need to be done is expose network locations to the apps file explorer _(as it currently will not show network locations)_ and change the command that is executed when a new project is created.

ie;
To create a junction: mklink /J linkName target
To create a symbolic link: mklink /D linkName target

### Version

2024.1.1

**Comment by po-trottier** [comment] 2024-02-05 22:05
Will be tracked under REMIX-2751

However it is possible we close this task without changing it because of the requirements for Symlinks.

Requiring admin privileges to create any symlink could be an issue. We will need to investigate that and make sure it doesn't break existing flows.

**Comment by NV-LL** [comment] 2024-05-02 22:46
Closing since fix was confirmed internally with 2024.3.0. Thank you for your suggestion!

**Closed by NV-LL** 2024-05-02 22:46 UTC
Labels: jira, feature, toolkit
