### ISSUE TITLE
Major visual bugs with the replacement lights.

### ISSUE THREAD

**Issue by UncleRito** [NVIDIAGameWorks/rtx-remix#367] opened 2024-01-26 20:02 UTC
- There is a bug with custom replacement lights where the light angle seems to be completely broken in a way that light is emitted in every direction except the place it's supposed to be emitting. Seems like the light angle value is inverted. The same happens with light focus where changing the focus value to anything other than the default causes the light to completely disappear. This is a big issue since it renders almost all types of light except for sphere and distant lights since all the shaping features are completely broken.
- Latest action builds as of writing
- RTX 4090
- Game ready driver 551.23
- Any game

**To Reproduce**
1. Make a capture
2. Add a stage light eg. Disk light
3. Change the light shaping options like cone angle, or focus
4. The light will behave unexpectedly

**Expected behavior**
- The lights should follow the shaping settings and look as expected.

**Screenshots**
Here is a small video demonstrating the problem in the toolkit. This issue is also present in-game using the runtime:
https://youtu.be/irAoYTGzKAg

I hope this issue can be resolved quickly since the game I'm working with needs very specific custom lighting which can not be achieved due to the current issues.

**Comment by traggey** [comment] 2024-01-26 20:04
Seconding this!

**Comment by Hemry81** [comment] 2024-01-26 20:25
Fixing the correct light casting is a "first priority" for a ray tracing engine.

**Comment by nicklllmedia** [comment] 2024-01-26 20:41
We've been craving for this since the start over 6 months ago

**Comment by anon-apple** [comment] 2024-01-26 20:44
You said it happens in-game too, is there a particular game you see this in? I ask because shaping is working correctly from my understanding in other games (last I checked at least), so it may be something game-specific or a new bug due to how the Remix Application is exporting replacement lights.

I will look into this though soon if possible to see if I can reproduce it.

**Comment by UncleRito** [comment] 2024-01-27 06:33
I have tested 2 games, NFS underground, and the sample project. I'm using the sample project in the little demonstration the youtube video above. Furthermore, this bug can also be seen in @Hemry81's video here. https://youtu.be/O8CS-Yj6by4
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/100042652/9f5198db-304a-40c1-b992-c0d4f0d91d94)

**Comment by UncleRito** [comment] 2024-01-27 06:37
And by light shaping, I specifically mean light focus, and cone angle settings. The light width, height, and radius settings work fine.

**Comment by Cyntonian** [comment] 2024-02-04 15:50
Hey, I can also confirm to have issues with this. I am currently playing around in Star Wars Battlefront 2 (2005). The issue I observed here is specifically with replacement distant lights and their rotation / angle settings. The rotation / angle in the runtime will be the exact opposite of what is shown in the toolkit. 

This forces me to currently have 2 distant lights, one for the runtime and one as a working light in the toolkit.

**Comment by anon-apple** [comment] 2024-02-05 18:44
@Cyntonian Distant lights don't use shaping so that is not quite the same as what is being discussed here, but it may be related since the Z axis of a light is used for many things like that (shaping, distant light direction, rect/disk light directions). Does that issue with the distant lights happen only in that game or does it happen in others too?

**Comment by Cyntonian** [comment] 2024-02-05 20:38
@anon-apple Hey, I have quickly bootstrapped a project with Portal for this. The distant light there behaves the same way as observed in BF2. I have to mirror the light angle in the toolkit to get it to show up correctly in the runtime.

Note: That Portal has Z up while BF2 does not use Z as up but Y. Nonetheless the behavior is the same.

**Comment by anon-apple** [comment] 2024-06-06 03:03
I think this should be fixed now as of https://github.com/NVIDIAGameWorks/dxvk-remix/commit/67cd53e9bd3b6945398a395739fb3bb2a3749b22. Feel free to re-open this issue if it was not fixed.

**Comment by NV-LL** [comment] 2024-06-06 17:26
Hi @UncleRito - we're going to leave this open for a bit so you can verify if the issue is resolved. Please let us know once you have the chance to check with the above build.

**Comment by UncleRito** [comment] 2024-06-09 01:12
Hi @NV-LL we did some testing and it seems like the issues have been fixed now. You can close this issue now.

**Closed** 2024-06-12 13:25 UTC
Labels: bug, jira, runtime
