### ISSUE TITLE
Sonic Adventure 2 launches with the RTX Remix menu, but RTX does not work

### ISSUE THREAD

**Issue by Veitaserum4** [NVIDIAGameWorks/rtx-remix#498] opened 2024-05-07 18:52 UTC
**Describe the bug**
- The RTX Remix menu appears in-game, but no RTX is present
- Remix 0.5.0
- EVGA RTX 2060 12GB
-  Geforce game ready driver 552.12
- Sonic Adventure 2 Battle (Steam) (No mod loader)

**Attach files!**
- [NvRemixBridge_01.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15239644/NvRemixBridge_01.log)
- [d3d9_01.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15239652/d3d9_01.log)
- [sonic2app_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15239653/sonic2app_d3d9.log)
- [rtx.conf.txt](https://github.com/NVIDIAGameWorks/rtx-remix/files/15239654/rtx.conf.txt)

**To Reproduce**
1.Extract RTX Remix in root game folder /common/Sonic Adventure 2
2.Launch game
3. See RTX Remix menu
4. No RTX is present during gameplay (Looks the same without RTX Remix)

**Expected behavior**
The game will have raytracing

**Screenshots**
![328634279-8e417077-ffb4-43e0-9d07-713aff3589e6](https://github.com/NVIDIAGameWorks/rtx-remix/assets/63559389/4c890de3-de6d-423f-ab80-e316027f4adf)

![328634279-8e417077-ffb4-43e0-9d07-713aff3589e6](https://github.com/NVIDIAGameWorks/rtx-remix/assets/63559389/1c4f0746-1750-40ab-999f-1f690c9f12e7)

**Comment by nv-ajaus** [comment] 2024-05-07 22:48
Hi @Veitaserum4 , this is a duplicate of #275 so I'm going to close this for now as it is already being tracked.

**Closed by nv-ajaus** 2024-05-07 22:48 UTC
