### ISSUE TITLE
Bully scholarship Edition

### ISSUE THREAD

**Issue by howdoicodeplease** [NVIDIAGameWorks/rtx-remix#165] opened 2023-05-19 11:55 UTC
**Describe the bug**
Game crashes on boot up
Remix 0.2.0
RTX 3070ti
Latest GPU driver
Steam

**Attach logs!**

[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11516588/NvRemixBridge.log)

[D3D9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11516582/D3D9.log)

[Bully_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11516579/Bully_d3d9.log)

**To Reproduce**
click on exe

**Expected behavior**
the game should boot to the menu
**Screenshots**

**Comment by Radeoxx** [comment] 2024-05-10 16:13
Hi, I do confirm that still crashes with and without latest SilentPatch instaled.
Version: remix-0.5.0+dac740ce

Freezes on intro video (logos), no frame update untill crashes, can hear video but all you see is splash image with RTX Remix popup that dissapears after 10 seconds reminding alt+x shortcut.

Clean installation:
[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15276879/d3d9.log)
[Bully_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15276884/Bully_d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15276897/NvRemixBridge.log)

And then
![image](https://github.com/NVIDIAGameWorks/rtx-remix/assets/12381901/e387f8af-9340-46f9-b4cd-188f6d1921d4)
(Updated DirectX Installation from redistributables and window is now blank)

SilentPatch: (Tried with dinput8.dll and dinput.dll ASI Loader)

[d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15277167/d3d9.log)
[NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/15277173/NvRemixBridge.log)

**Comment by NV-LL** [comment] 2024-05-10 18:22
Thank you for confirming! This looks to be the same issue as reported in #[461](https://github.com/NVIDIAGameWorks/rtx-remix/issues/461), which is tracked as REMIX-3036. We'll close this as a duplicate to keep our issue list clean, and I'll add this info to our internal ticket. You can subscribe to #[461](https://github.com/NVIDIAGameWorks/rtx-remix/issues/461) for updates, and to provide us any further info if you have it. Thanks!

**Comment by NV-LL** [comment] 2024-05-10 18:24
Dupe of #[461](https://github.com/NVIDIAGameWorks/rtx-remix/issues/461)

**Closed by NV-LL** 2024-05-10 18:24 UTC
Labels: bridge-server-init
