### ISSUE TITLE
Fallout new Vegas Crashes on launch

### ISSUE THREAD

**Issue by MCH2024** [NVIDIAGameWorks/rtx-remix#10] opened 2023-04-12 16:56 UTC
[12:52:41.432] info:  No default config found for: D:\SteamLibrary\steamapps\common\Fallout New Vegas\FalloutNV.exe
[12:52:41.432] info:  Trying to open config file: D:\SteamLibrary\steamapps\common\Fallout New Vegas\.trex\bridge.conf
[12:52:41.432] info:  Using shared heap for textures.
[12:52:41.432] info:  Using shared heap for static buffers.
[12:52:41.432] info:  Using shared heap for dynamic buffers.
[12:52:41.432] info:  ==================
[12:52:41.432] info:  NVIDIA RTX Remix Bridge Client
[12:52:41.432] info:  ==================
[12:52:41.433] info:  Version: remix-0.1.0
[12:52:41.434] info:  Loaded d3d9.dll from D:\SteamLibrary\steamapps\common\Fallout New Vegas\FalloutNV.exe
[12:52:41.548] info:  DirectInput8 hook attached.
[12:52:41.581] info:  DirectInput hook attached.
[12:52:41.583] info:  Initializing new shared memory object.
[12:52:41.617] info:  Shared memory: [ClientChannel_b3efc54c-1cba-48a0-a4af-89f9dd883cad] created and initialized successfully!
[12:52:41.619] info:  Initializing new shared memory object.
[12:52:41.630] info:  Shared memory: [ServerChannel_b3efc54c-1cba-48a0-a4af-89f9dd883cad] created and initialized successfully!
[12:52:41.631] info:  Initializing new shared memory object.
[12:52:41.632] info:  Shared memory: [SharedDataHeap_meta_b3efc54c-1cba-48a0-a4af-89f9dd883cad] created and initialized successfully!
[12:52:41.632] info:  Initializing new shared memory object.
[12:52:41.723] info:  Shared memory: [SharedDataHeap_data_0_b3efc54c-1cba-48a0-a4af-89f9dd883cad] created and initialized successfully!
[12:52:41.724] info:  Initializing new shared memory object.
[12:52:41.811] info:  Shared memory: [SharedDataHeap_data_1_b3efc54c-1cba-48a0-a4af-89f9dd883cad] created and initialized successfully!
[12:52:43.197] info:  Launching server with GUID b3efc54c-1cba-48a0-a4af-89f9dd883cad
[12:52:44.454] info:  Sending SYN command, waiting for ACK from server...
[12:52:48.605] info:  Ack received! Handshake completed! Telling server to continue waiting for commands...
[12:52:48.606] info:  Server crash recovery enabled
[12:52:49.504] info:  Creating a thread-safe D3D9 device.
[12:52:49.505] debug: Creating Device...
[12:52:49.506] debug: ...command queue successfully flushed...
[12:52:49.506] debug: ...server-side D3D9 device creation command sent...
[12:52:49.506] debug: ...waiting for create device ack response from server...
[12:52:53.099] debug: ...create device ack response received from server...
[12:52:53.099] debug: ...server-side D3D9 device successfully created...
[12:52:53.100] debug: ...Device successfully created!
[12:52:53.426] err:   The server process has unexpectedly exited, disabling bridge until next game relaunch!
[12:52:53.428] info:  [Uptime] Server (estimated): 11s
[12:52:53.434] err:   GetDeviceCaps() failed with: no response from server.
[12:52:53.482] info:  Client window became inactive, disabling timeouts for bridge client...
[12:52:57.516] info:  DirectInput keyboard acquired
[12:52:57.517] info:  DirectInput mouse acquired
[12:52:57.519] info:  Client window became active, reenabling timeouts for bridge client...
[12:52:57.528] info:  About to unload bridge client.
[12:52:57.528] info:  Sending Terminate command to server...
[12:52:57.603] info:  Shutdown cleanup successful, exiting now!
[12:52:57.604] info:  DirectInput8 hook detached.
[12:52:57.604] info:  DirectInput hook detached.
[12:52:57.604] info:  [Uptime]: 15s

**Comment by NV-DM** [comment] 2023-04-12 18:10
Hello. Thank you for submitting. Please attach NvRemixBridge.log which can be found in the .trex directory.

**Comment by MCH2024** [comment] 2023-04-13 20:25
[16:24:55.054] info:  No default config found for: D:\SteamLibrary\steamapps\common\Fallout New Vegas\FalloutNV.exe
[16:24:55.055] info:  Trying to open config file: D:\SteamLibrary\steamapps\common\Fallout New Vegas\.trex\bridge.conf
[16:24:55.056] info:  Using shared heap for textures.
[16:24:55.057] info:  Using shared heap for static buffers.
[16:24:55.058] info:  Using shared heap for dynamic buffers.
[16:24:55.059] info:  ==================
[16:24:55.060] info:  NVIDIA RTX Remix Bridge Server
[16:24:55.061] info:  ==================
[16:24:55.062] info:  Version: remix-0.1.0
[16:24:55.063] info:  Running in x64 mode!
[16:24:55.064] info:  Launched server with GUID 35de6dc2-b605-403d-9c90-738647d1810a
[16:24:55.065] info:  Shared memory: [ClientChannel_35de6dc2-b605-403d-9c90-738647d1810a] created and initialized successfully!
[16:24:55.065] debug: CreateSemaphore returned existing semaphore by the same name ClientDataQueue.
[16:24:55.065] info:  Shared memory: [ServerChannel_35de6dc2-b605-403d-9c90-738647d1810a] created and initialized successfully!
[16:24:55.065] debug: CreateSemaphore returned existing semaphore by the same name ServerDataQueue.
[16:24:55.066] info:  Shared memory: [SharedDataHeap_meta_35de6dc2-b605-403d-9c90-738647d1810a] created and initialized successfully!
[16:24:55.066] info:  Shared memory: [SharedDataHeap_data_0_35de6dc2-b605-403d-9c90-738647d1810a] created and initialized successfully!
[16:24:55.066] info:  Shared memory: [SharedDataHeap_data_1_35de6dc2-b605-403d-9c90-738647d1810a] created and initialized successfully!
[16:24:55.067] debug: CreateSemaphore returned existing semaphore by the same name Present.
[16:24:55.067] info:  Server started up, waiting for connection from client...
[16:24:55.067] info:  Registering exit callback in case client exits unexpectedly.
[16:24:55.068] info:  Registering message channel for asynchronous message handling.
[16:24:55.068] info:  Initializing D3D9...
[16:24:55.069] info:  Message channel MessageChannelServer established.
[16:24:56.704] info:  D3D9 interface object creation succeeded!
[16:24:56.705] info:  Loaded D3D9 from D:\SteamLibrary\steamapps\common\Fallout New Vegas\.trex\d3d9.dll
[16:24:56.705] warn:  Please note that the version of d3d9 loaded is NOT DXVK. Functional restrictions may apply.
[16:24:56.705] info:  Sync request received, sending ACK response...
[16:24:56.706] info:  Done! Now waiting for client to consume the response...
[16:24:56.706] info:  Handshake completed! Now waiting for incoming commands...
[16:24:56.719] info:  No leaked objects dicovered at Direct3D module eviction.
[16:25:01.662] info:  Server side D3D9 Device created successfully!
[16:25:01.662] debug: Sending CreateDevice ack response back to client.
[16:25:05.606] err:   The client process has unexpectedly exited, shutting down server as well!
[16:25:05.683] info:  Command processing loop finished, cleaning up and exiting...
[16:25:05.710] info:  Shutdown cleanup successful, exiting now!
[16:25:05.711] info:  [Uptime]: 10s

**Comment by MichaelTornberg** [comment] 2023-04-17 07:52
Flat-out refuses to work on Fallout New Vegas (Gog version) The log only says it unexpectedly shut down.. no other data. 

...
[09:43:26.651] info:  Server side D3D9 Device created successfully!
[09:43:26.652] debug: Sending CreateDevice ack response back to client. 
[09:43:27.138] err:   The client process has unexpectedly exited, shutting down server as well!
[09:43:27.652] info:  Command processing loop finished, cleaning up and exiting...
[09:43:27.671] info:  Shutdown cleanup successful, exiting now!
[09:43:27.671] info:  [Uptime]: 3s

**Comment by rdok** [comment] 2023-04-19 03:28
Confirming the same behaviour: the client unexpectedly exits with no helpful hint of the cause.

# Testing environment
GPU: RTX 3090
GPU driver: 531.68
Game version: 1.4.0.525
HDR: off
Store: [GOG](https://www.gog.com/en/game/fallout_new_vegas_ultimate_edition)
Display resolution: 2560x1440
Game Environment: 
 - Clean game with no mods installed
 - Uninstalled the game to ensure all mods are fully removed.
 - Restarted the machine
 - Ensured game runs fine without rtx-mixture   
 
Tested with lowest graphics settings to ensure exclude things like HDR, and water reflections.
 - Game resolution: 1920x1080
 - Vertical sync: off

# Logs
- [FalloutNVLauncher_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11268192/FalloutNVLauncher_d3d9.log)
- [FalloutNV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11268193/FalloutNV_d3d9.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11268194/d3d9.log)
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11268196/NvRemixBridge.log)

**Comment by WINDWAIK3R** [comment] 2023-04-20 00:52
Same issue with Fallout 3. Running 4gb patches seems to help somewhat with initial launch before crash.

**Comment by WallSoGB** [comment] 2023-04-26 08:23
Game's not using fixed pipeline so it's not going to work. Lights are done in material shaders.

**Comment by WallSoGB** [comment] 2023-04-26 08:32
> Confirming the same behaviour: the client unexpectedly exits with no helpful hint of the cause.
> 
> # Testing environment
> rtx-remix version: [0.1.1](https://github.com/NVIDIAGameWorks/rtx-remix/releases/tag/remix-0.1.1) GPU: RTX 3090 GPU driver: 531.68 Game version: 1.4.0.525 HDR: off Store: [GOG](https://www.gog.com/en/game/fallout_new_vegas_ultimate_edition) Display resolution: 2560x1440 Game Environment:
> 
> * Clean game with no mods installed
> * Uninstalled the game to ensure all mods are fully removed.
> * Restarted the machine
> * Ensured game runs fine without rtx-mixture
> 
> Tested with lowest graphics settings to ensure exclude things like HDR, and water reflections.
> 
> * Game resolution: 1920x1080
> * Vertical sync: off
> 
> # DLL Crash Logger
> [CobbCrashLogger.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11268317/CobbCrashLogger.log)
> 
> > GAME CRASHED AT INSTRUCTION Base+0x00AC8AB5 IN MODULE: S:\GOG Games\Fallout New Vegas\FalloutNV.exe
> > Please note that this does not automatically mean that that module is responsible.
> > It may have been supplied bad data or program state as the result of an issue in
> > the base game or a different DLL. -[Crash Logger ](https://www.nexusmods.com/newvegas/mods/72317)
> 
> # Logs
> * [FalloutNVLauncher_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11268192/FalloutNVLauncher_d3d9.log)
> * [FalloutNV_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11268193/FalloutNV_d3d9.log)
> * [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11268194/d3d9.log)
> * [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11268196/NvRemixBridge.log)
> 
> # Fallout 3
> Same issue on Fallout 3; Fallout New Vegas is based on the same engine.

Crashes on shader compilation - device's Pixel Shader version string is null.

**Comment by WallSoGB** [comment] 2023-04-26 08:36
No it's not. I mod this engine - the renderer in Creation Engine is remade for the most part.

**Comment by MichaelTornberg** [comment] 2023-04-26 08:42
It was still Gamebryo then (new vegas) but regardless.. nVidia make shader patches (even rewrites) for most games in their drivers. So I'm fairly certain they can fix shader problems (if that is what it is)

**Comment by WallSoGB** [comment] 2023-04-26 08:43
It's not Gamebryo either - sorry, but the renderer is custom in both games - NiDX9Renderer only functions as the D3D9 handler.

**Comment by MichaelTornberg** [comment] 2023-04-26 08:46
Well, I have no reason to doubt you :).. And I know they modded the engine when they bought the engine code for Fallout 3. But that's neither here nor there :) I'm just saying that I am quite certain nVidia have access on the level needed to fix the issue.

**Comment by NV-LL** [comment] 2024-05-06 19:16
Hello! Will you please check on the latest release and let us know if this issue persists? Thank you!

**Comment by Kim2091** [comment] 2024-05-06 22:08
@NV-LL The issues in this post have been resolved. I opened a new issue for anything else: https://github.com/NVIDIAGameWorks/rtx-remix/issues/423

**Comment by NV-LL** [comment] 2024-05-06 22:52
Excellent, thank you so much! We'll close this ticket and continue investigation on #423.

**Closed by NV-LL** 2024-05-06 22:52 UTC
