### ISSUE TITLE
TES4: Oblivion Crashes on Launch

### ISSUE THREAD

**Issue by GT500org** [NVIDIAGameWorks/rtx-remix#8] opened 2023-04-12 16:29 UTC
Oblivion seems to crash regardless of video settings after adding Remix files to its folder. Log file may indicate a shared memory issue:

```[12:15:15.975] info:  No default config found for: C:\Program Files (x86)\Steam\steamapps\common\Oblivion\Oblivion.exe
[12:15:15.975] info:  Trying to open config file: C:\Program Files (x86)\Steam\steamapps\common\Oblivion\.trex\bridge.conf
[12:15:15.975] info:  Using shared heap for textures.
[12:15:15.976] info:  Using shared heap for static buffers.
[12:15:15.976] info:  Using shared heap for dynamic buffers.
[12:15:15.976] info:  ==================
[12:15:15.976] info:  NVIDIA RTX Remix Bridge Client
[12:15:15.976] info:  ==================
[12:15:15.976] info:  Version: remix-0.1.0
[12:15:15.976] info:  Loaded d3d9.dll from C:\Program Files (x86)\Steam\steamapps\common\Oblivion\Oblivion.exe
[12:15:15.977] warn:  Injected DirectInput8Create proc detected!
[12:15:15.978] info:  DirectInput8 hook attached.
[12:15:15.979] warn:  Injected DirectInputCreate proc detected!
[12:15:15.997] info:  DirectInput hook attached.
[12:15:15.999] info:  Initializing new shared memory object.
[12:15:16.028] info:  Shared memory: [ClientChannel_b8a58967-73cf-4193-94d3-7208b63c84b0] created and initialized successfully!
[12:15:16.029] info:  Initializing new shared memory object.
[12:15:16.038] info:  Shared memory: [ServerChannel_b8a58967-73cf-4193-94d3-7208b63c84b0] created and initialized successfully!
[12:15:16.038] info:  Initializing new shared memory object.
[12:15:16.039] info:  Shared memory: [SharedDataHeap_meta_b8a58967-73cf-4193-94d3-7208b63c84b0] created and initialized successfully!
[12:15:16.039] info:  Initializing new shared memory object.
[12:15:16.129] info:  Shared memory: [SharedDataHeap_data_0_b8a58967-73cf-4193-94d3-7208b63c84b0] created and initialized successfully!
[12:15:16.130] err:   The shared memory map view could not be created (error code 8)!
```

Settings in bridge.conf don't seem to have any effect on the output in d3d9.log file. For instance changing `# useSharedHeap = True` to `useSharedHeap = False` seems to have no effect, as does changing `# sharedHeapPolicy = Textures, DynamicBuffers, StaticBuffers` to `sharedHeapPolicy = ` (the log still indicates that the Remix is using shared heap for the same things, and it still attempts to create and initialize shared memory).

**Comment by jhaapasa** [comment] 2023-04-12 16:36
Thanks for the report! We are looking into this.

**Comment by DarianLStephens** [comment] 2023-04-12 16:54
Assuming the Fixed Function Pipeline requirement still holds for RTX Remix, then this would probably be pretty normal, since Oblivion uses shaders.

**Comment by Rmurray2006** [comment] 2023-04-16 09:11
Yep can confirm uses the Shader 3 prefix

**Comment by AnatolySnegovskiy** [comment] 2023-04-18 17:08
Path 4gb https://www.nexusmods.com/oblivion/mods/45576?tab=files&file_id=1000008086
solves the rimix initialization problem.
But the game still does not start, the black screen hangs, the window mode also does not help.

Log d3d9.log

[19:31:53.218] info:  No default config found for: C:\Program Files (x86)\Steam\steamapps\common\Oblivion\Oblivion.exe
[19:31:53.218] info:  Trying to open config file: C:\Program Files (x86)\Steam\steamapps\common\Oblivion\.trex\bridge.conf
[19:31:53.218] info:  Using shared heap for textures.
[19:31:53.219] info:  Using shared heap for static buffers.
[19:31:53.219] info:  Using shared heap for dynamic buffers.
[19:31:53.219] info:  ==================
[19:31:53.219] info:  NVIDIA RTX Remix Bridge Client
[19:31:53.219] info:  ==================
[19:31:53.219] info:  Version: remix-0.1.1-2-gdc825b6
[19:31:53.219] info:  Loaded d3d9.dll from C:\Program Files (x86)\Steam\steamapps\common\Oblivion\Oblivion.exe
[19:31:53.220] warn:  Injected DirectInput8Create proc detected!
[19:31:53.220] info:  DirectInput8 hook attached.
[19:31:53.222] warn:  Injected DirectInputCreate proc detected!
[19:31:53.229] info:  DirectInput hook attached.
[19:31:53.229] info:  Initializing new shared memory object.
[19:31:53.255] info:  Shared memory: [ClientChannel_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully!
[19:31:53.255] info:  Initializing new shared memory object.
[19:31:53.264] info:  Shared memory: [ServerChannel_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully!
[19:31:53.265] info:  Initializing new shared memory object.
[19:31:53.265] info:  Shared memory: [SharedDataHeap_meta_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully!
[19:31:53.265] info:  Initializing new shared memory object.
[19:31:53.341] info:  Shared memory: [SharedDataHeap_data_0_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully!
[19:31:53.342] info:  Initializing new shared memory object.
[19:31:53.426] info:  Shared memory: [SharedDataHeap_data_1_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully!
[19:31:53.427] info:  Launching server with GUID fddeac15-c0c5-4357-b82f-477ecaf30e18
[19:31:53.441] info:  Sending SYN command, waiting for ACK from server...
[19:31:53.665] info:  Ack received! Handshake completed! Telling server to continue waiting for commands...
[19:31:53.665] info:  Server crash recovery enabled
[19:31:53.910] info:  Creating a thread-safe D3D9 device.
[19:31:53.910] debug: Creating Device...
[19:31:53.910] debug: ...server-side D3D9 device creation command sent...
[19:31:53.911] debug: ...waiting for create device ack response from server...
[19:31:55.123] debug: ...create device response received from server...
[19:31:55.123] debug: ...server-side D3D9 device successfully created...
[19:31:55.123] debug: ...Device successfully created!

Oblivion_d3d9.log:
info:  D3D9DeviceEx::ResetSwapChain:
info:    Requested Presentation Parameters
info:      - Width:              1024
info:      - Height:             768
info:      - Format:             D3D9Format::X8R8G8B8
info:      - Auto Depth Stencil: true
info:                  ^ Format: D3D9Format::D24S8
info:      - Windowed:           true
info:  Presenter: Actual swap chain properties:
info:    Format:       VK_FORMAT_B8G8R8A8_UNORM
info:    Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR
info:    Buffer size:  1024x768
info:    Image count:  2
info:    Exclusive FS: 2
info:  No winproc detected, initiating bridge message channel for: 0000000000020D48
warn:  Message channel UWM_REMIX_BRIDGE_REGISTER_THREADPROC_MSG handshake timeout. Retrying...
warn:  Message channel UWM_REMIX_BRIDGE_REGISTER_THREADPROC_MSG handshake timeout. Retrying...
...

**Comment by CyberAP** [comment] 2023-08-18 22:41
I can confirm it works well with the latest dxvk-remix and bridge-remix. Guide on how to install (sorry for Discord): https://discord.com/channels/1028444667789967381/1097339713062441031/1142198541721288875

**Comment by Rmurray2006** [comment] 2023-08-19 18:47
> Path 4gb https://www.nexusmods.com/oblivion/mods/45576?tab=files&file_id=1000008086 solves the rimix initialization problem. But the game still does not start, the black screen hangs, the window mode also does not help.
> 
> Log d3d9.log
> 
> [19:31:53.218] info: No default config found for: C:\Program Files (x86)\Steam\steamapps\common\Oblivion\Oblivion.exe [19:31:53.218] info: Trying to open config file: C:\Program Files (x86)\Steam\steamapps\common\Oblivion.trex\bridge.conf [19:31:53.218] info: Using shared heap for textures. [19:31:53.219] info: Using shared heap for static buffers. [19:31:53.219] info: Using shared heap for dynamic buffers. [19:31:53.219] info: ================== [19:31:53.219] info: NVIDIA RTX Remix Bridge Client [19:31:53.219] info: ================== [19:31:53.219] info: Version: remix-0.1.1-2-gdc825b6 [19:31:53.219] info: Loaded d3d9.dll from C:\Program Files (x86)\Steam\steamapps\common\Oblivion\Oblivion.exe [19:31:53.220] warn: Injected DirectInput8Create proc detected! [19:31:53.220] info: DirectInput8 hook attached. [19:31:53.222] warn: Injected DirectInputCreate proc detected! [19:31:53.229] info: DirectInput hook attached. [19:31:53.229] info: Initializing new shared memory object. [19:31:53.255] info: Shared memory: [ClientChannel_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully! [19:31:53.255] info: Initializing new shared memory object. [19:31:53.264] info: Shared memory: [ServerChannel_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully! [19:31:53.265] info: Initializing new shared memory object. [19:31:53.265] info: Shared memory: [SharedDataHeap_meta_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully! [19:31:53.265] info: Initializing new shared memory object. [19:31:53.341] info: Shared memory: [SharedDataHeap_data_0_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully! [19:31:53.342] info: Initializing new shared memory object. [19:31:53.426] info: Shared memory: [SharedDataHeap_data_1_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully! [19:31:53.427] info: Launching server with GUID fddeac15-c0c5-4357-b82f-477ecaf30e18 [19:31:53.441] info: Sending SYN command, waiting for ACK from server... [19:31:53.665] info: Ack received! Handshake completed! Telling server to continue waiting for commands... [19:31:53.665] info: Server crash recovery enabled [19:31:53.910] info: Creating a thread-safe D3D9 device. [19:31:53.910] debug: Creating Device... [19:31:53.910] debug: ...server-side D3D9 device creation command sent... [19:31:53.911] debug: ...waiting for create device ack response from server... [19:31:55.123] debug: ...create device response received from server... [19:31:55.123] debug: ...server-side D3D9 device successfully created... [19:31:55.123] debug: ...Device successfully created!
> 
> Oblivion_d3d9.log: info: D3D9DeviceEx::ResetSwapChain: info: Requested Presentation Parameters info: - Width: 1024 info: - Height: 768 info: - Format: D3D9Format::X8R8G8B8 info: - Auto Depth Stencil: true info: ^ Format: D3D9Format::D24S8 info: - Windowed: true info: Presenter: Actual swap chain properties: info: Format: VK_FORMAT_B8G8R8A8_UNORM info: Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR info: Buffer size: 1024x768 info: Image count: 2 info: Exclusive FS: 2 info: No winproc detected, initiating bridge message channel for: 0000000000020D48 warn: Message channel UWM_REMIX_BRIDGE_REGISTER_THREADPROC_MSG handshake timeout. Retrying... warn: Message channel UWM_REMIX_BRIDGE_REGISTER_THREADPROC_MSG handshake timeout. Retrying... ...

threadpolicy needs to be set to 1 in dxvk or bridge

**Comment by Rmurray2006** [comment] 2023-08-19 18:49
> > Path 4gb https://www.nexusmods.com/oblivion/mods/45576?tab=files&file_id=1000008086 solves the rimix initialization problem. But the game still does not start, the black screen hangs, the window mode also does not help.
> > Log d3d9.log
> > [19:31:53.218] info: No default config found for: C:\Program Files (x86)\Steam\steamapps\common\Oblivion\Oblivion.exe [19:31:53.218] info: Trying to open config file: C:\Program Files (x86)\Steam\steamapps\common\Oblivion.trex\bridge.conf [19:31:53.218] info: Using shared heap for textures. [19:31:53.219] info: Using shared heap for static buffers. [19:31:53.219] info: Using shared heap for dynamic buffers. [19:31:53.219] info: ================== [19:31:53.219] info: NVIDIA RTX Remix Bridge Client [19:31:53.219] info: ================== [19:31:53.219] info: Version: remix-0.1.1-2-gdc825b6 [19:31:53.219] info: Loaded d3d9.dll from C:\Program Files (x86)\Steam\steamapps\common\Oblivion\Oblivion.exe [19:31:53.220] warn: Injected DirectInput8Create proc detected! [19:31:53.220] info: DirectInput8 hook attached. [19:31:53.222] warn: Injected DirectInputCreate proc detected! [19:31:53.229] info: DirectInput hook attached. [19:31:53.229] info: Initializing new shared memory object. [19:31:53.255] info: Shared memory: [ClientChannel_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully! [19:31:53.255] info: Initializing new shared memory object. [19:31:53.264] info: Shared memory: [ServerChannel_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully! [19:31:53.265] info: Initializing new shared memory object. [19:31:53.265] info: Shared memory: [SharedDataHeap_meta_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully! [19:31:53.265] info: Initializing new shared memory object. [19:31:53.341] info: Shared memory: [SharedDataHeap_data_0_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully! [19:31:53.342] info: Initializing new shared memory object. [19:31:53.426] info: Shared memory: [SharedDataHeap_data_1_fddeac15-c0c5-4357-b82f-477ecaf30e18] created and initialized successfully! [19:31:53.427] info: Launching server with GUID fddeac15-c0c5-4357-b82f-477ecaf30e18 [19:31:53.441] info: Sending SYN command, waiting for ACK from server... [19:31:53.665] info: Ack received! Handshake completed! Telling server to continue waiting for commands... [19:31:53.665] info: Server crash recovery enabled [19:31:53.910] info: Creating a thread-safe D3D9 device. [19:31:53.910] debug: Creating Device... [19:31:53.910] debug: ...server-side D3D9 device creation command sent... [19:31:53.911] debug: ...waiting for create device ack response from server... [19:31:55.123] debug: ...create device response received from server... [19:31:55.123] debug: ...server-side D3D9 device successfully created... [19:31:55.123] debug: ...Device successfully created!
> > Oblivion_d3d9.log: info: D3D9DeviceEx::ResetSwapChain: info: Requested Presentation Parameters info: - Width: 1024 info: - Height: 768 info: - Format: D3D9Format::X8R8G8B8 info: - Auto Depth Stencil: true info: ^ Format: D3D9Format::D24S8 info: - Windowed: true info: Presenter: Actual swap chain properties: info: Format: VK_FORMAT_B8G8R8A8_UNORM info: Present mode: VK_PRESENT_MODE_IMMEDIATE_KHR info: Buffer size: 1024x768 info: Image count: 2 info: Exclusive FS: 2 info: No winproc detected, initiating bridge message channel for: 0000000000020D48 warn: Message channel UWM_REMIX_BRIDGE_REGISTER_THREADPROC_MSG handshake timeout. Retrying... warn: Message channel UWM_REMIX_BRIDGE_REGISTER_THREADPROC_MSG handshake timeout. Retrying... ...
> 
> threadpolicy needs to be set to 1 in dxvk or bridge

not to mention, in the project i've started in discord. we use the dxvk portion and delete the bridge config in the trex folder

**Comment by mirh** [comment] 2024-05-01 00:20
So.. I seem to understand this could be closed?

**Comment by NV-LL** [comment] 2024-05-06 19:14
Thank you for confirming! We'll close this out.

**Closed by NV-LL** 2024-05-06 19:14 UTC
Labels: jira
