### ISSUE TITLE
Disney-Pixar Cars (2006) Client crash after few seconds in menu

### ISSUE THREAD

**Issue by danylohetmantsev** [NVIDIAGameWorks/rtx-remix#196] opened 2023-06-12 13:57 UTC
**Describe the bug**
- A clear and concise description of what the bug is.
Game crashes after few seconds in menu.
- Which Remix version (include branch and commit info for dxvk and bridge if not a stable build)
0.2.0
- Which GPU
RTX4090
- Which GPU driver version
531.34
- Which game build (and whether it is from Steam/GOG/Other)
Other

**Attach logs!**
- [NvRemixBridge.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11723990/NvRemixBridge.log)
- [d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11724015/d3d9.log)
- [Cars_d3d9.log](https://github.com/NVIDIAGameWorks/rtx-remix/files/11723993/Cars_d3d9.log)

**To Reproduce**
1. Start game.
2. Crashes after a second in menu after intro videos.

**Expected behavior**
Game is not crashing.

**Comment by szlobipeti** [comment] 2023-07-14 07:34
The cause of this issue has been identified and an issue for the specific crash has been opened: #216

**Comment by nv-ajaus** [comment] 2023-08-08 18:36
@danylohetmantsev @szlobipeti , can either of you please retry to reproduce this issue using the latest bridge-remix-nv and dxvk-remix-nv?

**Comment by nv-ajaus** [comment] 2023-08-08 19:56
Confirmed that the crash is resolved with szlobipeti on the RTX Remix Showcase discord channel.

**Closed by nv-ajaus** 2023-08-08 19:56 UTC
Labels: bug, bridge-client-crash

**Comment by LoginPro** [comment] 2023-10-11 17:06
Could you please explain how you managed to correct this problem?

**Comment by szlobipeti** [comment] 2023-10-12 11:33
it was fixed by itself when using the latest build of rtx-remix
I have not touched the project in a while, so idk if it still works, but I would assume so
