### ISSUE TITLE
RDNA 3 D3D error

### ISSUE THREAD

**Issue by KingVulpes** [NVIDIAGameWorks/rtx-remix#497] opened 2024-05-07 01:39 UTC
Failed to create D3D device 
happens on all RDNA 3 GPUs using drivers above 23.12.1
-GPU (RX 7600)
-Driver (24.4.1)

Steps to reproduce: Just try to load a game like Portal RTX on a RDNA 3 GPU using the latest drivers

note: this only happens on newer runtimes

**Comment by anon-apple** [comment] 2024-05-07 21:05
This has already been fixed and is just pending being merged in. Internally the issue is REMIX-3033. Will close this when it is finally merged.

**Comment by anon-apple** [comment] 2024-05-08 18:46
This should be fixed now as of https://github.com/NVIDIAGameWorks/dxvk-remix/commit/b061137f4daa5018e44da5d57103d327694446f8.

**Closed by anon-apple** 2024-05-08 18:46 UTC
Labels: bug, jira, runtime
