### ISSUE TITLE
[Toolkit bug]: AI Tools do not free video memory

### ISSUE THREAD

**Issue by ArturAlekseev** [NVIDIAGameWorks/rtx-remix#411] opened 2024-02-09 19:49 UTC
### Describe the bug

After texture upscale video memory goes full and does not cleared.

### How do you reproduce the bug?

Open AI Tools and process a dds texture into PNG files.

### What is the expected behavior?

Free video memory after processing texture.

### Version

2024.1.1

**Comment by po-trottier** [comment] 2024-02-12 20:14
This is a duplicate of this issue: https://github.com/NVIDIAGameWorks/rtx-remix/issues/310 which was fixed and will be available in the next release of the app!

**Closed by po-trottier** 2024-02-12 20:14 UTC
Labels: bug, toolkit, triage
